### ISSUE TITLE
Architecture #1 - Affichage des IN sur la carte

### ISSUE THREAD

**Issue by kolok** [betagouv/SPPNautInterface#104]
- Peut-on produire des WMS ? Est-ce que Leaflet pourra l'absorber ? Essayons de bénéficier des standards existants dans le domaine pour démultiplier les usages possibles.
- **2 parties** : Front-Office (à l'attention des navigateurs principalement) & Back-Office (à l'attention des agents du SHOM).
    - ***Front-Office*** : On présente : 
        - une carte contenant les objets : BDGS + nouveaux objets (normés S1xy)
        - une zone de recherche d'objets, zones
        - une section d'affichage des parties des IN où les objets sont mentionnés
        - un "popup" qui permet d'avoir les descriptions fines d'un objet en particulier
        - On peut retrouver la géométrie d'un alinéa, sous-para, para, etc, via les objets qu'ils contiennent; ou on leur donne leur propre géométrie ?
    - ***Back-Office*** :
        - On se contente de Django Admin aussi longtemps que possible
        - On présente une zone de recherche :
            - pour récupérer l'identifiant d'un objet en BDGS (via flux WMS data shom)
            - (ou) pour créer un identifiant pour un objet non-BDGS et pouvoir créer sa géométrie (via une carte par exemple)
        - On crée 3 tables (ou +): 
            - [BDGS] une copie de la table BDGS via le flux WMS data shom
            - [BDTS] une table des objets / entités terrestres (nouveaux / non-BDGS) avec leur description fine selon la norme S1xy
            - [BPN] une table des ouvrages IN (xml) qui reprend tous les ouvrages xml (mis à jour 1 fois par semaine) avec les liaisons aux objets
- Dans les fichiers XML, on ajoute des **bpnId** sur tous les éléments à géolocaliser : objet, toponyme (qui seront soit dans la BDGS soit dans la BDTS), alinea, ssPara, sPara, para, sChapitre, chapitre, ouvrage. Plusieurs bpnId peuvent faire référence au même élément BDGS ou BDTS ou autre (theme, polygone)

![Image](https://user-images.githubusercontent.com/3653/215116021-77939abe-baf6-4a14-a542-2f6df1dd58b0.png)

**Comment by kolok** [comment]
1. Un clic sur un element de l'IN, affiche l'élément sur une carte

document.xml -> document.xml avec bpn_id
- [ ]  script pose des bpn_id sur les balises ...

document.xml avec bpn_id -> BDD
- [ ] creation d'une application carting dans le projet django SPPNautInterface
- [ ] table bpn_objects (bpn_id, typology, content, xpath)
- [ ] script intepret le document.xml avec bpn_id et qui l'enregistre dans la BDD

Géolocaliser un bpn_object [Étape intermediaire et potentiellement provisoire]
- [ ] ajout d'un champ geometry
- [ ] possibilité d'enregistrer une géometry pour un bpn_object via django_admin (à investiguer : geo_django)

Affichage d'une section (à investiguer : en utilisant le XPath) et lien avec la carte
- [ ] champ de saisie pour le xpath ou autre
- [ ] affichage de la section mentionnée
- [ ] au clic sur un élément, affichage sur la carte, exemple:
  - pour un alinéa, quand on clique sur le numéro d'alinéa, si la geometry existe, elle est affichée sur la carte
  - pour un chapitre ou paragraphe, quand on clique sur le titre, …
  - …

2. lien avec des objects BDGS

- [ ] appel du flux WMS datashom et enregistrement en BDD
- [ ] création de la table BDGS
- [ ] ajout des champs bdgs_id des la table bpn_objects ou d'une table de lien typée 
- [ ] lien possible entre bpn_object et bdgs_object

3. BDTS

Possibilité d'enrichir la donnée de la table bpn_objects avec un objet bdts_object
Doit s'inspirer de la norme s100

4. Cartographie

Quand on selectionne une zone ou un element de la carte, les IN couvrant cette zone sont affichée

**Comment by rik** [comment]
Partie 1 faite dans https://github.com/betagouv/SPPNautInterface/pull/102
