### ISSUE TITLE
Cas des toponymes dans une liste (d'un alinéa)

### ISSUE THREAD

**Issue by JulieMoncorger** [betagouv/SPPNautInterface#136]
Les toponymes (et peut-être autres cas) inclus dans une liste d'un alinéa ne sont pas ingérés en base de données
Exemple : b820f987-cdee-477f-8e59-4e2b5f523a28 (dans 4.3.2.0.13)

Peut-être qu'on peut changer les toponymes avec du XPath de ce genre :
```py
ouvrage.find('.//*[@bpn_id="37a6971a-c827-42f9-a728-0c51e7b54236"]')
```

**Comment by rik** [comment]
On a 6520 lignes en BDD, 6734 `bpn_id` dans le XML. Oups…
