### ISSUE TITLE
[radiocommunications.signalFrequency] What is the unit ?

### ISSUE THREAD

**Issue by JulieMoncorger** [betagouv/SPPNautInterface#240]
radiocommunications.signalFrequency has an Integer type in PDF and [XSD](https://github.com/betagouv/SPPNautS1xyModelisation/blob/6dc55b14127c19cd0f722eb292668fa033811224/S127/XSD/S127/1.0.0/20181129/S127.xsd#L2678) but the unit for this attribute is not specified. Is it dB ?
Also this field has no description.

**Comment by rik** [comment]
We haven't used this field yet and we don't think it's important for now.
